name: Build Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -o gt-linux-amd64

        # Windows
        GOOS=windows GOARCH=amd64 go build -o gt-windows-amd64.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gt-linux-amd64
          gt-windows-amd64.exe
        generate_release_notes: true
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
