# Homebrew tap update workflow (reference only, not used for ghtask)
# Kept for organizational purposes - can be adapted for other projects

name: Update Homebrew

on:
  workflow_dispatch:  # Manual trigger only (disabled)

permissions:
  contents: write

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update Homebrew tap
      env:
        GITHUB_TOKEN: ${{ secrets.TAP_UPDATE_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION_NO_V="${VERSION#v}"

        # Calculate sha256 from already-built binaries
        SHA_DARWIN_ARM64=$(shasum -a 256 gt-darwin-arm64 | cut -d' ' -f1)
        SHA_DARWIN_AMD64=$(shasum -a 256 gt-darwin-amd64 | cut -d' ' -f1)
        SHA_LINUX_ARM64=$(shasum -a 256 gt-linux-arm64 | cut -d' ' -f1)
        SHA_LINUX_AMD64=$(shasum -a 256 gt-linux-amd64 | cut -d' ' -f1)

        echo "Checksums calculated for ${VERSION}"

        # Clone tap repo with authentication
        git clone https://x-access-token:${GITHUB_TOKEN}@github.com/DeprecatedLuar/homebrew-tap.git
        cd homebrew-tap/Formula

        # Update formula
        cat > ghtask.rb <<'EOF'
        class Ghtask < Formula
          desc "Lightweight CLI for managing GitHub Issues"
          homepage "https://github.com/DeprecatedLuar/ghtask"
          version "VERSION_NO_V_PLACEHOLDER"
          license "MIT"

          on_macos do
            if Hardware::CPU.arm?
              url "https://github.com/DeprecatedLuar/ghtask/releases/download/VERSION_PLACEHOLDER/gt-darwin-arm64"
              sha256 "SHA_DARWIN_ARM64_PLACEHOLDER"
            else
              url "https://github.com/DeprecatedLuar/ghtask/releases/download/VERSION_PLACEHOLDER/gt-darwin-amd64"
              sha256 "SHA_DARWIN_AMD64_PLACEHOLDER"
            end
          end

          on_linux do
            if Hardware::CPU.arm?
              url "https://github.com/DeprecatedLuar/ghtask/releases/download/VERSION_PLACEHOLDER/gt-linux-arm64"
              sha256 "SHA_LINUX_ARM64_PLACEHOLDER"
            else
              url "https://github.com/DeprecatedLuar/ghtask/releases/download/VERSION_PLACEHOLDER/gt-linux-amd64"
              sha256 "SHA_LINUX_AMD64_PLACEHOLDER"
            end
          end

          def install
            bin.install "gt-darwin-arm64" => "gt" if OS.mac? && Hardware::CPU.arm?
            bin.install "gt-darwin-amd64" => "gt" if OS.mac? && Hardware::CPU.intel?
            bin.install "gt-linux-arm64" => "gt" if OS.linux? && Hardware::CPU.arm?
            bin.install "gt-linux-amd64" => "gt" if OS.linux? && Hardware::CPU.intel?
          end

          test do
            assert_match "gt", shell_output("#{bin}/gt --help")
          end
        end
        EOF

        # Replace placeholders
        sed -i "s/VERSION_NO_V_PLACEHOLDER/${VERSION_NO_V}/g" ghtask.rb
        sed -i "s/VERSION_PLACEHOLDER/${VERSION}/g" ghtask.rb
        sed -i "s/SHA_DARWIN_ARM64_PLACEHOLDER/${SHA_DARWIN_ARM64}/g" ghtask.rb
        sed -i "s/SHA_DARWIN_AMD64_PLACEHOLDER/${SHA_DARWIN_AMD64}/g" ghtask.rb
        sed -i "s/SHA_LINUX_ARM64_PLACEHOLDER/${SHA_LINUX_ARM64}/g" ghtask.rb
        sed -i "s/SHA_LINUX_AMD64_PLACEHOLDER/${SHA_LINUX_AMD64}/g" ghtask.rb

        # Commit and push
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ghtask.rb
        git commit -m "Auto-update formula to ${VERSION}" || exit 0
        git push

        echo "✅ Homebrew formula updated to ${VERSION}"
